CREATE TABLE public.listings (
	id serial4 NOT NULL,
	item_id text NOT NULL,
	"source" text NOT NULL,
	city text NULL,
	url text NULL,
	title text NULL,
	price int4 NULL,
	published_at timestamp NULL,
	address text NULL,
	metro _text NULL,
	description text NULL,
	property_type text NULL,
	rooms int4 NULL,
	room_type text NULL,
	floor int4 NULL,
	area_total numeric(8, 2) NULL,
	area_living numeric(8, 2) NULL,
	area_kitchen numeric(8, 2) NULL,
	ceiling_height numeric(4, 2) NULL,
	renovation text NULL,
	bathroom text NULL,
	windows text NULL,
	furniture text NULL,
	appliances text NULL,
	balcony bool NULL,
	loggia bool NULL,
	wardrobe bool NULL,
	panoramic_windows bool NULL,
	warm_floor bool NULL,
	house_type text NULL,
	total_floors int4 NULL,
	year_built int4 NULL,
	passenger_elevator int4 NULL,
	cargo_elevator int4 NULL,
	yard text NULL,
	parking text NULL,
	concierge bool NULL,
	garbage_chute bool NULL,
	gas bool NULL,
	demolition_planned bool NULL,
	sale_method text NULL,
	sale_conditions text NULL,
	developer text NULL,
	sale_type text NULL,
	lat numeric(10, 7) NULL,
	lon numeric(10, 7) NULL,
	parsed_at timestamp DEFAULT now() NULL,
	CONSTRAINT listings_item_id_source_key UNIQUE (item_id, source),
	CONSTRAINT listings_pkey PRIMARY KEY (id)
);